spring:
  cloud:
    sentinel:
      transport:
        dashboard: 47.93.245.153:8858
        port: 8719
  profiles:
    include: test
  datasource:
    username: root
    password: Key123456
    url: jdbc:mysql://47.93.245.153:3308/library?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
    tomcat:
      time-between-eviction-runs-millis: 18800
  redis:
    port: 6379
    host: 47.107.34.224
  application:
    name: library
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dominikyang.library.entity
server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  config: log.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql

